added boot on 127.0.0.1 (to have a green icon) and re-integrate the p12 export for certificate.

diff --git a/code/install/paquet/home/snack/scripts/createCertificate b/code/install/paquet/home/snack/scripts/createCertificate
--- a/code/install/paquet/home/snack/scripts/createCertificate
+++ b/code/install/paquet/home/snack/scripts/createCertificate
@@ -51,13 +51,21 @@ then
 	exit 3
 fi
 
+# Export to p12 format
+openssl pkcs12 -password pass: -export -in $USERFILESPATH/$USERCERT -inkey $USERFILESPATH/$USERKEY -out $USERFILESPATH/$USERP12 -clcerts
+if [ ! $? -eq 0 ]
+then
+	echo "Export to p12 format failed!"
+	exit 4
+fi
+
 # Update certificate revocation list to authorize this certificate
 openssl ca -config /etc/ssl/openssl.cnf -gencrl -out ${CERTS_DIR}/crl/crl.pem
 
 if [ ! $? -eq 0 ]
 then
 	echo "Revocation list update failed!"
-	exit 4
+	exit 5
 fi
 
 exit 0
