Update certs scripts

diff --git a/code/install/paquet/home/snack/scripts/revokeClient b/code/install/paquet/home/snack/scripts/revokeClient
--- a/code/install/paquet/home/snack/scripts/revokeClient
+++ b/code/install/paquet/home/snack/scripts/revokeClient
@@ -1,32 +1,33 @@
 #!/bin/sh
 
-PAQUETNAME=snack
-USER_HOME=/home
-DESTPATH=$USER_HOME/$PAQUETNAME/cert
-USERFILESPATH=$DESTPATH/users
-
-
-if [ ! $# -eq 1 ]
+if [ ! $# -eq 2 ]
 then
-        if [ $# -gt 1 ]
-        then
-                echo "Usage: createClient [name]"
-                echo "No more argument needed"
-                exit
-        else
-                read -p "Enter user name: " USERNAME
-        fi
+	echo "Usage: revokeClient CertsDirectory Username"
+	exit 1
 else
-        USERNAME=$1
-
+	CERTSPATH=$1
+        USERNAME=$2
 fi
 
 
 USERCERT=${USERNAME}_cert.pem
 
-openssl ca -config /etc/ssl/openssl.cnf -revoke $USERFILESPATH/$USERCERT
+# Revoke certificate.
+openssl ca -config /etc/ssl/openssl.cnf -revoke ${CERTSPATH}/users/${USERCERT}
 
+if [ ! $? -eq 0 ]
+then
+	echo "Certificate revocation failed!"
+	exit 5
+fi
 
-#CRL regeneration.
+# Certificate revocation list update.
+openssl ca -config /etc/ssl/openssl.cnf -gencrl -out ${CERTSPATH}/crl/crl.pem
 
-openssl ca -config /etc/ssl/openssl.cnf -gencrl -out $DESTPATH/crl/crl.pem
+if [ ! $? -eq 0 ]
+then
+	echo "Revocation list update failed!"
+	exit 4
+fi
+
+exit 0
